#
# This is a small board with only 64KB of flash and 8KB of RAM, and whilst
# the configuration builds it currently does not flash successfully.
#
name = "demo-stm32g031-nucleo"
target = "thumbv6m-none-eabi"
board = "stm32g031"
stacksize = 944

[kernel]
path = "."
name = "demo-stm32g0-nucleo"
requires = {flash = 11800, ram = 2048}
features = ["g031", "panic-halt"]
stacksize = 640

[supervisor]
notification = 1

[outputs.flash]
address = 0x08000000
size = 65536
read = true
execute = true

[outputs.ram]
address = 0x20000000
size = 8192
read = true
write = true
execute = false  # let's assume XN until proven otherwise

[tasks.jefe]
path = "../../task/jefe"
name = "task-jefe"
priority = 0
requires = {flash = 4096, ram = 512}
start = true
features = ["log-null"]
stacksize = 352

[tasks.rcc_driver]
path = "../../drv/stm32g0-rcc"
name = "drv-stm32g0-rcc"
priority = 1
requires = {flash = 1024, ram = 512}
uses = ["rcc"]
start = true
features = ["g031"]
stacksize = 512

[tasks.idle]
path = "../../task/idle"
name = "task-idle"
priority = 5
requires = {flash = 128, ram = 256}
stacksize = 256
start = true

[peripherals.rcc]
address = 0x40021000
size = 1024
